
import java.beans.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author tocur
 */
public class test extends javax.swing.JFrame {

    /**
     * Creates new form test
     */
    public test() {
        initComponents();
        Connect();
        try {
            LoadIntrebare ();
        } catch (SQLException ex) {
            Logger.getLogger(test.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    int Verificarerasp=0;
  int marks=0;
    String cor=null;
    String Raspuns=null;
     
     Statement stat;
    public boolean VerificareRasp()
    {
        
    String Raspunsraspuns="";
    
    if(r1.isSelected())
    {
     Raspunsraspuns=r1.getText();
}
    else if(r2.isSelected())
    {
    Raspunsraspuns=r2.getText();

}else if(r3.isSelected())
    {
   Raspunsraspuns=r3.getText();
}
    else if(r4.isSelected())
    {
    Raspunsraspuns=r4.getText();
}
     if( Raspunsraspuns.equals(cor)&&(Raspuns==null||Raspuns.equals(cor)))
      {
          marks=marks+1;
          txtmarks.setText(String.valueOf(marks));
      }
      else if( !Raspunsraspuns.equals(cor)&&Raspuns!=null)
      {
          if( marks > 0) {
              marks= marks - 1;
          }
          txtmarks.setText(String.valueOf(marks));
      }
    
    //pastrarea raspunsului
    if(!Raspunsraspuns.equals("")){

    try {
    String query="UPDATE question SET RaspunsDat=? WHERE Intrebare=?";
    pst=con.prepareStatement(query);
    pst.setString(1,Raspunsraspuns);
    pst.setString(2, jLabel4.getText());
    pst.execute();

}catch(SQLException ex){
    ex.printStackTrace();
}
    return true;
}
    //cand butonul este selectat
    return false;
}

    private void RaspunsNull(){
    try {
    String query="UPDATE question SET RaspunsDat=? ";
    pst=con.prepareStatement(query);
    pst.setString(1,null);
    pst.execute();
}catch(SQLException ex){
    ex.printStackTrace();
}
}

    private boolean RaspunsDat1(){
    try {
    String query="SELECT RaspunsDat FROM question WHERE Intrebare='"+jLabel4.getText()+"'";
     java.sql.Statement  stat=con.prepareStatement(query);
    ResultSet res=stat.executeQuery(query);
    while(res.next()){
   Raspuns=res.getString("RaspunsDat");
    if(Raspuns ==null){
    return false;
}
    break;
}
      if(r1.getText().equals(Raspuns)){
        r1.setSelected(true);
} 
       else if(r2.getText().equals(Raspuns)){
        r2.setSelected(true);
} 
       else if(r3.getText().equals(Raspuns)){
        r3.setSelected(true);
} 
    else if(r4.getText().equals(Raspuns)){
        r4.setSelected(true);
} 
     
}catch(SQLException ex){
    System.out.println("Exception Caught");
    ex.printStackTrace();
} 
    return true;
    
}
     String  CorrectAns=null;
 Connection con;
    PreparedStatement pst;
    ResultSet rs;
public void Connect()
{
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost/onlineexam","root","");
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(question.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(question.class.getName()).log(Level.SEVERE, null, ex);
        }
}
    public void LoadIntrebare () throws SQLException{
    String query="select * from question";
    Statement stat=null;
     java.sql.Statement  stat1 = con.createStatement();
    rs=stat1.executeQuery(query);
    while(rs.next()){
        
        jLabel4.setText(rs.getString(2));
         r1.setText(rs.getString(3));
           r2.setText(rs.getString(4));
             r3.setText(rs.getString(5));
               r4.setText(rs.getString(6));
              CorrectAns=rs.getString(7);
              break;
    }
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        r1 = new javax.swing.JRadioButton();
        r2 = new javax.swing.JRadioButton();
        r3 = new javax.swing.JRadioButton();
        r4 = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtmarks = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        buttonGroup1.add(r1);
        r1.setText("jRadioButton1");

        buttonGroup1.add(r2);
        r2.setText("jRadioButton1");

        buttonGroup1.add(r3);
        r3.setText("jRadioButton1");

        buttonGroup1.add(r4);
        r4.setText("jRadioButton1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(r4)
                    .addComponent(r2)
                    .addComponent(r1)
                    .addComponent(r3))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(r1)
                .addGap(18, 18, 18)
                .addComponent(r2)
                .addGap(18, 18, 18)
                .addComponent(r3)
                .addGap(27, 27, 27)
                .addComponent(r4)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        jButton3.setText("Next");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Online Test");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Intrebare:");

        txtmarks.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtmarks.setForeground(new java.awt.Color(255, 0, 0));
        txtmarks.setText("Marks:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(txtmarks))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGap(23, 23, 23)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtmarks)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       
        if(VerificareRasp()){
            try {
                if(rs.next())
                {
                    jLabel4.setText(rs.getString("Intrebare"));
                   r1.setText(rs.getString(3));
           r2.setText(rs.getString(4));
             r3.setText(rs.getString(5));
               r4.setText(rs.getString(6));
               cor=rs.getString(7);
               if(!RaspunsDat1()){
                   buttonGroup1.clearSelection();
               }
                }
                else {
                    JOptionPane.showMessageDialog(this,"This is first record of student");
                }
            }
            catch(Exception e){
                e.printStackTrace(); 
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new test().setVisible(true);
            }
        });
    }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r2;
    private javax.swing.JRadioButton r3;
    private javax.swing.JRadioButton r4;
    private javax.swing.JLabel txtmarks;
    // End of variables declaration//GEN-END:variables
}
